// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gateway

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"nacostest/app/gateway/biz"
	"nacostest/app/gateway/conf"
	"nacostest/app/gateway/data"
	"nacostest/app/gateway/data/grpc"
	"nacostest/app/gateway/server"
	"nacostest/app/gateway/service"
	"nacostest/pkg/component/discovery"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(env *conf.Env, config *discovery.Config, confServer *conf.Server, logger log.Logger) (*kratos.App, error) {
	registryDiscovery, err := discovery.NewDiscovery(config)
	if err != nil {
		return nil, err
	}
	userClient, err := grpc.NewUserClient(registryDiscovery)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(userClient, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := service.NewUserService(userUseCase)
	authClient, err := grpc.NewAuthClient(registryDiscovery)
	if err != nil {
		return nil, err
	}
	authRepo := data.NewAuthRepo(authClient, logger)
	authUseCase := biz.NewAuthUseCase(authRepo, logger)
	authService := service.NewAuthService(authUseCase)
	httpServer := server.NewHTTPServer(confServer, userService, authService, logger)
	app := newApp(env, httpServer)
	return app, nil
}
